apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 15gi-hdd-rwo
  namespace: demo-deployment-rwo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ionos-enterprise-hdd
  resources:
    requests:
      storage: 15Gi