apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: demo-podaffinity-wordpress
  annotations:
    kubernetes.io/change-cause: "Initial deployment"  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: database
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: username
        - name: WORDPRESS_DB_PASSWORD_FILE
          value: /secrets/password
        volumeMounts:
        - name: secret
          mountPath: /secrets
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - mysql
      volumes:    
      - name: secret
        secret:
          secretName: mysql-secret
          defaultMode: 0400
