apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo-podaffinity-wordpress
type: Opaque
data:
  # The password is: password
  password: cGFzc3dvcmQK
  root-password: cGFzc3dvcmQK