.PHONY: foo-website
foo-website:
	docker compose -f foo-website/docker-compose.yml build

.PHONY: multicontainer-pod-nginx
multicontainer-pod-nginx:
	docker compose -f multicontainer-pod-nginx/docker-compose.yml build