apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: test-data
  containers:
  - name: quiz-api
    image: nginx
    ports:
    - name: http
      containerPort: 8080
    volumeMounts:
    - name: test-volume
      mountPath: /mnt
