apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "ionos-enterprise-hdd"
  volumeName: test-pv
