apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir
  namespace: demo-emptydir
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emptydir-pod
  template:
    metadata:
      labels:
        app: emptydir-pod
    spec:
      initContainers:
        - name: init-emptydir
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "touch /cache/`date +%Y%m%d-%H:%M:%S`-`hostname`-init.txt"]
          volumeMounts:
            - mountPath: /cache
              name: cache-volume

      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}        
