apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: demo-configmaps

spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/config/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /config
      name: config
  volumes:
    - name: config
      configMap:
        name: redis-config-map
        items:
        - key: redis-config
          path: redis.conf