apiVersion: v1
kind: Pod
metadata:
  namespace: demo-replicaset
  name: frontend-pod
  labels:
    tier: frontend
spec:
  containers:
    - name: php-redis
      image: gcr.io/google_samples/gb-frontend:v3