apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-ts-claim
  namespace: demo-ts-pvandpvc
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "ionso-enterprise-hdd"
  volumeName: shared-data-ts-volume # We claim a particular volume by using this property