apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: demo-ts-pvandpvc
spec:
  volumes:
  - name: shared-data-volume
    persistentVolumeClaim:
      claimName: shared-data-claim
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: http
      containerPort: 80
    volumeMounts:
    - name: shared-data-volume
      mountPath: /mnt/shared-data
